### ISSUE TITLE
Thickness fill problem in multi-series radial progress bar

### ISSUE THREAD

**Issue by damooo** [okrad/svelte-progressbar#10]
When we have mult-series redial progress bars, It is only filling thickness for last series-item, but  adding only stroke for remaining items.

Here is repl: [https://svelte.dev/repl/d1b872b0762d48e6b8095ef98dfbdb4c?version=3.24.1](https://svelte.dev/repl/d1b872b0762d48e6b8095ef98dfbdb4c?version=3.24.1)

**Comment by okrad** [comment]
Thank you, it should be fixed now...

**Comment by damooo** [comment]
`_/\_`, Working great now.
