### ISSUE TITLE
Add typings

### ISSUE THREAD

**Issue by smcelhinney** [okrad/svelte-progressbar#11]
Using svelte with Typescript and this module produces the following error

```
Could not find a declaration file for module '@okrad/svelte-progressbar'. '.../node_modules/@okrad/svelte-progressbar/index.js' implicitly has an 'any' type.
  Try `npm install @types/okrad__svelte-progressbar` if it exists or add a new declaration (.d.ts) file containing `declare module '@okrad/svelte-progressbar';`
```
and adding 
```
declare module '@okrad/svelte-progressbar';
``` 
to typings file results in an `resovles to an untyped module` error. 

Would be great to have these typings baked into the library.

**Comment by okrad** [comment]
Hi @smcelhinney, initial TypeScript support has just landed with version 1.9.0! Can you check it out?
