### ISSUE TITLE
Percentage labels are wrongly positioned

### ISSUE THREAD

**Issue by albertms10** [okrad/svelte-progressbar#12]
The content of this `div` element is rendered at the top-left limit of the first wrapping `relative` HTML element.

```html
<div
  class="progress-value-content svelte-mnjwk" 
  style="font-size: 40%; color: rgb(85, 85, 85); top: -2px;"
>
  80%
</div>
```

Maybe the root `svg` element needs a `position: relative` CSS property or somewhat else.

A screenshot of what I see in the official page:

<img width="626" alt="Captura de Pantalla 2020-09-21 a les 12 52 45" src="https://user-images.githubusercontent.com/26429103/93759259-28a50f80-fc0a-11ea-8710-8bb356f80114.png">

**Comment by okrad** [comment]
Hi @albertms10, which browser are you using? I don't have any problems with chrome or firefox...

**Comment by albertms10** [comment]
Yes, you’re wright. I was using the latest stable Safari version (14.0), but on both Chrome or Firefox it look great!
It seems like there’s something going on under the hood in this new release…

**Comment by okrad** [comment]
It looks to be a [bug](https://bugs.webkit.org/show_bug.cgi?id=23113) in webkit... 

Someone suggested a possible workaround, I'll try to find find out if it really works...

**Comment by zakaria-chahboun** [comment]
i get the same issue in both browsers (Brave (chrome based), Firefox)

![image](https://user-images.githubusercontent.com/18173275/97372639-630e6600-18b4-11eb-93c8-72c5a04b929c.png)

**Comment by okrad** [comment]
Hi @zakaria-chahboun, I'm not able to reproduce your issue... 
Do you have the same (mis)behaviour even in the [examples page](https://okrad.github.io/svelte-progressbar/)?

**Comment by zakaria-chahboun** [comment]
@okrad no! but in my project i have this issue! also i create a new svelte project, and i get the same issue!

**Comment by zakaria-chahboun** [comment]
@okrad when i put the progress inside a div with center in css, the text is centered! but it remains at the top!

**Comment by okrad** [comment]
Did you include the index.css file? 
...Anyway, with the new version it isn't needed anymore, the position of the text should be ok now... Can you confirm it?

**Comment by zakaria-chahboun** [comment]
@okrad 

Yeah! Thanks! 😍

![Screenshot from 2020-11-07 04-03-44](https://user-images.githubusercontent.com/18173275/98430536-535e0100-20ae-11eb-8e63-e6f9416cbb04.png)
