### ISSUE TITLE
Option for rounded edges on the linear bar

### ISSUE THREAD

**Issue by seaneking** [okrad/svelte-progressbar#13]
Would be great to either have a prop for enabling rounded (rather than square) end-caps on the linear progress bars, or for having more hooks into the underlying styling etc.

**Comment by okrad** [comment]
Hi @seaneking, with the latest version (1.9.0) you can now use 2 new props: `rx` (horizontal border radius) and `ry` (vertical border radius). When `ry` isn't specified it defaults to `rx`...

**Comment by seaneking** [comment]
Awesome thanks!
