### ISSUE TITLE
foreignObject mask not working in Chrome/Chromium 88

### ISSUE THREAD

**Issue by zqianem** [okrad/svelte-progressbar#19]
Causes percentage text to remain dark as progress bar covers it.

Previous behavior (Chromium 87 / Firefox):
![image](https://user-images.githubusercontent.com/47396035/105735952-4361fa80-5f02-11eb-8bab-584ecef09de3.png)

Current behavior (Chromium 88):
![image](https://user-images.githubusercontent.com/47396035/105735683-fc740500-5f01-11eb-84f2-c00b0197d8bc.png)

Observed on both Linux and Windows.

**Comment by okrad** [comment]
Nice catch! I had to add an external "g" tag and move the mask reference there to make it work. 
I guess it is more correct indeed...
