### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by emiola** [okrad/svelte-progressbar#2]
Using exactly the example code for the svelte app, I see a couple of warnings:

![image](https://user-images.githubusercontent.com/379310/62062491-b1830f80-b1ee-11e9-8137-129c3835c964.png)

Defining the thickness prevents the latest, but I wonder if it's worth looking at the first one. Thanks.

**Comment by okrad** [comment]
Yes, I see... Those messages didn't show up with the old svelte version...

I'll take a look.

**Comment by okrad** [comment]
Hi @emiola, the new version (just released) should solve the problem.

**Comment by emiola** [comment]
Yes, I confirm, no warnings anymore. Grazie!
