### ISSUE TITLE
Are there any plans to make this compatible with sveltekit?

### ISSUE THREAD

**Issue by wetmarble** [okrad/svelte-progressbar#24]

**Comment by okrad** [comment]
Hi @wetmarble, I'd love to, but in my daily job I'm forced to use the bundled version and currently it seems [quite difficult](https://github.com/sveltejs/kit/issues/2572) to create it for libraries with sveltekiit.

**Comment by okrad** [comment]
Closing, as the library is now SvelteKit compatible!
