### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by emiola** [okrad/svelte-progressbar#3]
Updating the bar, I see an error:

`Error: <stop> attribute offset: Expected number or percentage, "NaN%".`,

coming from this [row](https://github.com/okrad/svelte-progressbar/blob/fcbd94e6ab01c392690bd11fd451516a67b05b73/src/Stop.svelte#L8).

**Comment by okrad** [comment]
How are you updating the bar?

**Comment by emiola** [comment]
I think it's simply a divide by zero issue.

See here:

```js
<script>
  import ProgressBar from "@okrad/svelte-progressbar";

  export let series = [];
  export let thickness = 0;

  let bar;

  const updateBar = values => {
    values.map((v, i) => bar.updatePerc(v, i));
  };

  const resetBar = () => {
    updateBar([0, 0]);
  };
</script>

<ProgressBar bind:this={bar} {series} />

<button on:click={() => updateBar([100, 100])}>update</button>
<button on:click={resetBar}>reset</button>
```

`resetBar()` triggers the issue.

**Comment by okrad** [comment]
You were right, it was a division by zero... Now it should be solved.
