### ISSUE TITLE
Сompatible with version svelte 4.0.0

### ISSUE THREAD

**Issue by mihrich** [okrad/svelte-progressbar#38]
Please make it compatible with Svelte v. 4.0.0
![err](https://github.com/okrad/svelte-progressbar/assets/1442402/177b0d18-a0ac-4295-b440-e49f4d9c2ac3)

**Comment by Pete-Y-CS** [comment]
I think I've resolved this. Tried to push a PR just now but don't have permissions.  https://www.npmjs.com/package/@megapenthes/svelte4-progressbar.

Hopefully this will do for now, I don't really have any intention of hijacking this or maintaining this 😅
