### ISSUE TITLE
Radial bar color behavior on 100% progress

### ISSUE THREAD

**Issue by loversandcode** [okrad/svelte-progressbar#4]
Hello, thanks for this awesome component. I use it in my dashboard project, and i have a question:
Is there some special way to make color different on different progress, for example green on <50%, yellow on 50-80% and red on 80-100% for radial progressbar?

For now I'm become to solution that i'm checking value each time it's changes and set color for it, but I face problem, when value become 100% it's not colored red, it's becoming transparent.

Can you please tell me how i can work out with these issue?

**Comment by okrad** [comment]
Hi @loversandcode, the feature you ask is on the roadmap (I need it too in my projects), and some work has already been done. I hope to find the time to release an updated version soon...

**Comment by loversandcode** [comment]
@okrad Thanks a lot! This is very useful feature! Will be waiting for that!

**Comment by okrad** [comment]
@loversandcode , I just published version 1.4.0, with color thresholds customization... Take a look at the "examples" paragraph in the readme to find out how to use it...

**Comment by loversandcode** [comment]
I check it out, and it's very nice thank you so much, you saved my day!

So far i don't see any issues on it
