### ISSUE TITLE
FEATURE Request: Semi Circle progress bar

### ISSUE THREAD

**Issue by Yahatix** [okrad/svelte-progressbar#6]

**Comment by okrad** [comment]
Hi @Yahatix, yes that'd be cool, I'll add it to the roadmap!

**Comment by okrad** [comment]
Hey @Yahatix, check out the newest release (1.6.0)... 
You can now set the _semicircle_ style to create a semicircular progress bar!

For example:
```svelte
<ProgressBar style="semicircle" series=[50] />
```

**Comment by bkd** [comment]
Great addition - just that the semi-circle visible element isnt really working that well. its visible range is from 6% to 50%, anything either side of this range is not visible

**Comment by okrad** [comment]
Thank you, now it should be fixed...
There was a type conversion anomaly in the arc rendering function.
